### Site metadata

# Don't make the title longer than this, otherwise it gets covered in mobile view.
title: adaaaaaaadsasd's Blog
description: My small blog

email:
twitter_username:
github_username: adaaaaaaadsasd
rss:

### Build settings

url: https://adaaaaaaadsasd.github.io
baseurl: /

permalink: pretty

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  tools:
    output: true
  languages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - docs/
  - vendor/
  - Gemfile # Gemfile.lock is implied because of how matching works.
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true
